services:
  # Backend API Service
  - type: web
    name: healthcare-backend
    env: node
    plan: starter
    buildCommand: cd backend && npm install
    startCommand: cd backend && npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3001
    healthCheckPath: /health
    autoDeploy: true

  # Frontend Web Service
  - type: web
    name: healthcare-frontend
    env: node
    plan: starter
    buildCommand: cd frontend && npm install && npm run build
    startCommand: cd frontend && npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3000
      - key: NEXT_PUBLIC_BACKEND_URL
        value: https://healthcareproject-39oy.onrender.com
      - key: BACKEND_URL
        value: https://healthcareproject-39oy.onrender.com
    healthCheckPath: /
    autoDeploy: true
